spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db-mycat-vip:8066/bu_oms?useUnicode=true&amp;characterEncoding=utf-8
      username: admin
      password: 9MeRMf7b15SvsjLpQFtB
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  http:
    encoding: UTF-8

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chenhl.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true


my:
  hello:
    nickname: aaa
    age: 34
    hometown: 安徽阜阳